version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./app:/app:cached
      - node_modules:/app/node_modules
    working_dir: "/app"
    ports:
      - "3000:3000"
    command: sh -c "yarn dev"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    ports:
      - 4000:4000
      - 9099:9099
      - 4400:4400
      - 4500:4500
    volumes:
      - ./firebase.json:/opt/firebase/firebase.json
    working_dir: /opt/firebase
    command: firebase emulators:start --project ${FIREBASE_PROJECT_ID}
    tty: true
volumes:
  postgres:
  node_modules:
